### ISSUE TITLE
How to make brush from texture?

### ISSUE THREAD

**Issue by rashidabbas** [Authman2/Canvas#10]
Dear Sir I have used your framework its working is awesome but I need to create brush from texture . kindly help me how to create brush tool from image texture like painting brushes.

just like this demo.
https://github.com/Harley-xk/MaLiang

thanks in advance.

**Comment by Authman2** [comment]
Please take a look at my updated version of Canvas which does allow for brush textures!

https://github.com/Authman2/Canvas2

**Comment by csd998aaa** [comment]
> Please take a look at my updated version of Canvas which does allow for brush textures!
> 
> https://github.com/Authman2/Canvas2

hello, this repositories cannot be opened anymore. Is there any other access path to the repositories?
